name: Build CI

on:
  push:
    branches: [master]
    paths:
      - "exporter/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      working-directory: ./exporter
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Install bit-bin
        run: sudo npm install bit-bin -g

        name: Init bit
        run: bit init
        working-directory: ${{env.working-directory}}

        name: Import bit components
        run: bit import komarov-sergey.sk-lib/app
        working-directory: ${{env.working-directory}}

      - name: Config bit
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
          bit config
        working-directory: ${{env.working-directory}}

      - name: Install compiler
        run: npm i @bit/bit.envs.compilers.react-typescript
        working-directory: ${{env.working-directory}}

      - name: Import bit
        run: |
          bit -v && bit import
        working-directory: ${{env.working-directory}}
        
      - name: Export bit
        run: |
          bit status
          bit tag -a
          bit export
        working-directory: ${{env.working-directory}}
